# Generated by Django 5.2.3 on 2025-07-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(help_text='Apercu visible gratuitement')),
                ('content', models.TextField(help_text="Contenu de l'article avec abonnement")),
                ('is_premium', models.BooleanField(default=True, help_text="l'article est il reserve aux abonnés ?")),
                ('published_at', models.DateTimeField(auto_now_add=True, help_text="Date de publication de l'article")),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_images/')),
            ],
        ),
    ]
