# Generated by Django 5.2.3 on 2025-07-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text="L'utilisateur est-il abonné ?"),
        ),
    ]
